import assert from "node:assert/strict";
import type { AllocationBranch, RestBoundary, RestInterval, WeeklyRestAllocationContext } from "../src/rest-engine/types.ts";
import { allocationContinuationSeed, allocationFrontierFromBranches } from "../src/rest-engine/allocation-frontier.ts";
import { allocationSolverContinuationContext, prepareAllocationChoiceGroups, solveOneShotWeeklyRestAllocations, solveSegmentedWeeklyRestAllocationsFromSeed } from "../src/rest-engine/weekly-rest-allocation.ts";
import { generateWeeklyRestComponentOptions } from "../src/rest-engine/weekly-rest-candidates.ts";
import { formatLondonInstant, resolveLondonWallTime } from "../src/rest-engine/time.ts";
const H=3600000, W1="2026-02-02", W2="2026-02-09", W3="2026-02-16", W4="2026-02-23"; let passed=0;
const test=(id:string,body:()=>void)=>{body();passed++;console.log(`PASS ${id}`)};
const at=(d:string,t="00:00:00")=>resolveLondonWallTime(d,t).epochMilliseconds as number;
const b=(n:number,role:RestBoundary["role"]):RestBoundary=>{const x=formatLondonInstant(n);return {sourceFactIds:["fixture"],role,time:resolveLondonWallTime(x.wallDate,x.wallTime),epochMilliseconds:n}};
const rest=(id:string,d:string,h:number,t="00:00:00"):RestInterval=>{const s=at(d,t),e=s+h*H;return{restIntervalId:id,startBoundary:b(s,"WORK_END"),endBoundary:b(e,"WORK_START"),startEpochMilliseconds:s,endEpochMilliseconds:e,observedThroughEpochMilliseconds:e,elapsedMilliseconds:e-s,elapsedRangeMilliseconds:null,supportingFactIds:[id],state:"CLOSED",provenance:"EXPLICIT",reviewStatus:"CLEAR",reviewReasons:[]}};
const ctx=(weeks:string[]):WeeklyRestAllocationContext=>({evaluationWeekIds:weeks,asOfEpochMilliseconds:at("2026-03-05"),historyStartEpochMilliseconds:at(W1),factualCoverageCompleteThroughAsOf:true});
const opts=(v:RestInterval[])=>generateWeeklyRestComponentOptions(v).options;
function seed(prefix:RestInterval[],weeks:string[]){const result=solveOneShotWeeklyRestAllocations(prefix,opts(prefix),ctx(weeks));const frontier=allocationFrontierFromBranches(result.branches);return {frontier,seed:allocationContinuationSeed(frontier,null),contexts:frontier.alternatives.map(x=>allocationSolverContinuationContext(x))}}
function solve(prefix:RestInterval[], prefixWeeks:string[], suffix:RestInterval[], suffixWeeks:string[]){const p=seed(prefix,prefixWeeks); return { ...p, outcome:solveSegmentedWeeklyRestAllocationsFromSeed(p.seed,suffix,opts(suffix),ctx(suffixWeeks),p.contexts) };}
test("ALC2-01",()=>{const x=solve([rest("p1","2026-02-03",45)],[W1],[rest("s1","2026-02-10",45)],[W2]);assert.ok(x.outcome.result.branches.length>0)});
test("ALC2-02",()=>{const x=solve([rest("p2","2026-02-03",45)],[W1],[rest("s2","2026-02-10",24)],[W2]);assert.ok(x.outcome.result.branches.some(b=>b.twoWeekEvaluations.some(e=>e.firstWeekId===W1&&e.secondWeekId===W2)))});
test("ALC2-03",()=>{const x=solve([rest("p3","2026-02-03",45)],[W1],[rest("s3","2026-02-10",45)],[W2]);assert.ok(x.outcome.result.branches.some(b=>b.rollingCycleResets.some(e=>e.previousRestIntervalId==="p3"&&e.nextRestIntervalId==="s3")))});
test("ALC2-04",()=>{const left=seed([rest("anchor-a","2026-02-03",45)],[W1]).frontier.alternatives[0];const right=seed([rest("anchor-b","2026-02-05",45)],[W1]).frontier.alternatives[0];assert.ok(left&&right);const joined={alternatives:[left,right]};const continuation=allocationContinuationSeed(joined,null);const contexts=joined.alternatives.map(x=>allocationSolverContinuationContext(x));const out=solveSegmentedWeeklyRestAllocationsFromSeed(continuation,[rest("s4","2026-02-10",45)],opts([rest("s4","2026-02-10",45)]),ctx([W2]),contexts);assert.deepEqual(new Set(contexts.map(c=>c.rollingAnchor?.restIntervalId)),new Set(["anchor-a","anchor-b"]));assert.ok(out.result.branches.some(b=>b.rollingCycleResets.some(e=>e.previousRestIntervalId==="anchor-a"&&e.nextRestIntervalId==="s4")));assert.ok(out.result.branches.some(b=>b.rollingCycleResets.some(e=>e.previousRestIntervalId==="anchor-b"&&e.nextRestIntervalId==="s4")))});
test("ALC2-05",()=>{const cross=rest("cross","2026-02-08",45,"12:00:00");const x=solve([cross],[W1,W2],[rest("s5","2026-02-17",45)],[W3]);assert.ok(x.frontier.alternatives.some(a=>a.assignments.some(z=>z.restIntervalId===undefined)||a.assignments.length>0));assert.ok(x.outcome.result.branches.length>0)});
test("ALC2-06",()=>{const edge=rest("edge","2026-02-08",45,"12:00:00");const p=seed([rest("before-edge","2026-02-03",45)],[W1]);const contexts=p.frontier.alternatives.map(x=>allocationSolverContinuationContext(x,edge));const out=solveSegmentedWeeklyRestAllocationsFromSeed(p.seed,[],[],ctx([W2]),contexts);assert.ok(out.result.branches.some(b=>b.components.some(c=>c.restIntervalId==="edge")));assert.ok(out.result.branches.every(b=>b.components.filter(c=>c.restIntervalId==="edge").length<=1));assert.equal(contexts[0]?.factualBoundaryRestInterval?.startEpochMilliseconds,edge.startEpochMilliseconds);assert.equal(contexts[0]?.factualBoundaryRestInterval?.endEpochMilliseconds,edge.endEpochMilliseconds)});
test("ALC2-07",()=>{const p=seed([rest("reduced","2026-02-03",24)],[W1]);const before=p.frontier.alternatives.flatMap(a=>a.reducedSourceSeeds);assert.ok(before.length>0);const out=solveSegmentedWeeklyRestAllocationsFromSeed(p.seed,[rest("s7","2026-02-10",45)],opts([rest("s7","2026-02-10",45)]),ctx([W2]),p.contexts);const after=allocationFrontierFromBranches(out.result.branches).alternatives.flatMap(a=>a.reducedSourceSeeds);assert.ok(before.some(x=>after.some(y=>JSON.stringify(x)===JSON.stringify(y))))});
test("ALC2-08",()=>{const x=solve([rest("p8","2026-02-03",45)],[W1],[rest("s8","2026-02-10",45)],[W2]);assert.deepEqual(x.outcome.diagnostics,{genesisEntered:false,historicalChoiceGroupsReplayed:0,historicalFixedWeeksReconstructed:0,historicalRollingCyclesRecomputed:0,suffixChoiceGroupsProcessed:1,startingFrontierAlternatives:x.frontier.alternatives.length,endingFrontierAlternatives:x.outcome.result.branches.length,finalizedHistoricalItemsRecreatedLive:0});assert.ok(!x.outcome.result.branches.some(b=>b.rollingQualifyingRests.some(r=>r.restIntervalId==="p8")))});
test("ALC2-09",()=>{const pre=[rest("m1","2026-02-03",45),rest("m2","2026-02-10",30)];const suf=[rest("m3","2026-02-17",45),rest("m4","2026-02-24",24)];const x=solve(pre,[W1,W2],suf,[W3,W4]);assert.ok(x.outcome.result.branches.length>0);assert.ok(x.outcome.result.branches.every(b=>b.twoWeekEvaluations.every(e=>e.firstWeekId!==W1||e.secondWeekId===W2||e.secondWeekId===W3)))});
console.log(`ALC2 matrix: ${passed}/9 PASS`);
