import assert from "node:assert/strict";
import type { AllocationBranch, RestBoundary, RestInterval, WeeklyRestAllocationContext } from "../src/rest-engine/types.ts";
import { allocationFrontierAlternative, allocationFrontierFromBranches } from "../src/rest-engine/allocation-frontier.ts";
import { finalizeAllocationFrontier } from "../src/rest-engine/allocation-finalization.ts";
import { formatLondonInstant, resolveLondonWallTime } from "../src/rest-engine/time.ts";
import { generateWeeklyRestComponentOptions } from "../src/rest-engine/weekly-rest-candidates.ts";
import { solveOneShotWeeklyRestAllocations } from "../src/rest-engine/weekly-rest-allocation.ts";

const HOUR = 60 * 60 * 1000; let passed = 0;
function test(id: string, name: string, body: () => void) { body(); passed += 1; console.log(`PASS ${id} — ${name}`); }
function instant(date: string, time = "00:00:00") { const value = resolveLondonWallTime(date, time); assert.equal(value.resolution, "VALID"); return value.epochMilliseconds as number; }
function boundary(epochMilliseconds: number, role: RestBoundary["role"]): RestBoundary { const civil = formatLondonInstant(epochMilliseconds); return { sourceFactIds: ["af"], role, time: resolveLondonWallTime(civil.wallDate, civil.wallTime), epochMilliseconds }; }
function rest(id: string, date: string, hours: number, time = "00:00:00"): RestInterval { const start = instant(date, time); const end = start + hours * HOUR; return { restIntervalId: id, startBoundary: boundary(start, "WORK_END"), endBoundary: boundary(end, "WORK_START"), startEpochMilliseconds: start, endEpochMilliseconds: end, observedThroughEpochMilliseconds: end, elapsedMilliseconds: end-start, elapsedRangeMilliseconds: null, supportingFactIds: [id], state: "CLOSED", provenance: "EXPLICIT", reviewStatus: "CLEAR", reviewReasons: [] }; }
function solve(intervals: RestInterval[], weeks: string[]): AllocationBranch[] { const context: WeeklyRestAllocationContext = { evaluationWeekIds: weeks, asOfEpochMilliseconds: instant("2026-03-09"), historyStartEpochMilliseconds: instant(weeks[0]), factualCoverageCompleteThroughAsOf: true, priorQualifyingWeeklyRest: { componentId: "prior", restIntervalId: "prior", endEpochMilliseconds: instant("2026-01-28"), reviewStatus: "CLEAR", reviewReasons: [] } }; return solveOneShotWeeklyRestAllocations(intervals, generateWeeklyRestComponentOptions(intervals).options, context).branches; }
const W1="2026-02-02", W2="2026-02-09", W3="2026-02-16", W4="2026-02-23", W5="2026-03-02";
const regularHistory = () => solve([rest("w1", "2026-02-03",45), rest("w2", "2026-02-10",45), rest("w3", "2026-02-17",45)], [W1,W2,W3]);
const completeHistory = () => { const branch = regularHistory().find((item) => item.fixedWeekAssignments.length === 3); assert.ok(branch, "AF fixture requires the real three-week counted lineage"); return [branch]; };
function frontier(branches: AllocationBranch[]) { return { alternatives: branches.map((branch) => allocationFrontierAlternative(branch)) }; }

test("AF1", "simple old regular allocation finalizes while historical result remains", () => { const result=finalizeAllocationFrontier(frontier(completeHistory()), {chronologicalBoundaryFixedWeekId:W3}); assert.ok(result.finalizedAllocationResults.length>0); assert.ok(result.liveFrontier.alternatives.every((a)=>a.assignments.every((x)=>x.fixedWeekId>=W2))); });
test("AF2", "immediately preceding fixed week remains live", () => { const result=finalizeAllocationFrontier(frontier(completeHistory()), {chronologicalBoundaryFixedWeekId:W2}); assert.equal(result.finalizedAllocationResults.length,0); assert.ok(result.liveFrontier.alternatives.some((a)=>a.assignments.some((x)=>x.fixedWeekId===W1))); });
test("AF3", "cross-week ownership alternatives remain separate while trailing", () => { const branches=solve([rest("cross","2026-02-07",45,"12:00:00")],[W1,W2]); const result=finalizeAllocationFrontier(frontier(branches),{chronologicalBoundaryFixedWeekId:W2}); assert.equal(result.liveFrontier.alternatives.length,branches.length); });
test("AF4", "extended old cross-week history emits reviewable finalized detail", () => { const branches=solve([rest("cross","2026-02-07",45,"12:00:00"),rest("later","2026-02-17",45)],[W1,W2,W3]); const result=finalizeAllocationFrontier(frontier(branches),{chronologicalBoundaryFixedWeekId:W4}); assert.ok(result.finalizedAllocationResults.length>0); assert.ok(result.finalizedAllocationResults.every((x)=>x.finalizedResultId && x.assignments.length)); });
test("AF5", "finalized reduced allocation retains its seed without live old component", () => { const branches=solve([rest("reduced","2026-02-03",30),rest("regular","2026-02-10",45)],[W1,W2]); const result=finalizeAllocationFrontier(frontier(branches),{chronologicalBoundaryFixedWeekId:W3}); const matching=result.liveFrontier.alternatives.find((a)=>a.reducedSourceSeeds.some((s)=>s.restIntervalId==="reduced")); assert.ok(matching); assert.equal(matching.countedComponents.some((c)=>c.restIntervalId==="reduced"),false); assert.ok(result.finalizedAllocationResults.some((x)=>x.countedComponents.some((c)=>c.restIntervalId==="reduced"))); });
test("AF6", "old rolling history collapses but latest anchor remains", () => { const result=finalizeAllocationFrontier(frontier(completeHistory()),{chronologicalBoundaryFixedWeekId:W4}); assert.ok(result.liveFrontier.alternatives.every((a)=>a.rollingAnchor?.restIntervalId==="w3")); assert.ok(result.finalizedAllocationResults.some((x)=>x.countedComponents.some((c)=>c.restIntervalId==="w1"))); });
test("AF7", "different possible latest anchors remain correlated alternatives", () => { const a=allocationFrontierAlternative(regularHistory()[0]); const b={...a, rollingAnchor:{...a.rollingAnchor!,restIntervalId:"other",componentId:"other",endEpochMilliseconds:999999}}; const result=finalizeAllocationFrontier({alternatives:[a,b]},{chronologicalBoundaryFixedWeekId:W4}); assert.equal(result.liveFrontier.alternatives.length,2); });
test("AF8", "same visible status with different future assignments does not merge", () => { const branches=solve([rest("cross","2026-02-07",45,"12:00:00")],[W1,W2]); const result=finalizeAllocationFrontier(frontier(branches),{chronologicalBoundaryFixedWeekId:W2}); assert.ok(result.liveFrontier.alternatives.length>=2); });
test("AF9", "finalized-only payload no longer blocks future-state canonicalization", () => { const branch=completeHistory()[0]; const a=allocationFrontierAlternative(branch); const b={...a, branchFingerprint:"another-history", countedComponents:[...a.countedComponents], assignments:[...a.assignments]}; const result=finalizeAllocationFrontier({alternatives:[a,b]},{chronologicalBoundaryFixedWeekId:W4}); assert.equal(result.liveFrontier.alternatives.length,1); assert.ok(result.finalizedAllocationResults.length>=1); });
test("AF10", "long manageable sequence retains current observable allocation and bounds live frontier", () => { const intervals=[rest("l1","2026-02-03",45),rest("l2","2026-02-10",45),rest("l3","2026-02-17",45),rest("l4","2026-02-24",45),rest("l5","2026-03-03",45)]; const branches=solve(intervals,[W1,W2,W3,W4,W5]).filter((branch)=>branch.fixedWeekAssignments.length===5); const before=frontier(branches); let current=before; const finalized=[] as ReturnType<typeof finalizeAllocationFrontier>["finalizedAllocationResults"][number][]; let max=current.alternatives.length; for(const week of [W3,W4,W5]) { const step=finalizeAllocationFrontier(current,{chronologicalBoundaryFixedWeekId:week}); finalized.push(...step.finalizedAllocationResults); current=step.liveFrontier; max=Math.max(max,current.alternatives.length); } assert.ok(current.alternatives.length<=max); assert.ok(finalized.length>0); assert.ok(current.alternatives.every((a)=>a.assignments.some((x)=>x.fixedWeekId===W4||x.fixedWeekId===W5))); console.log(`AF10 metrics: oldBranches=${before.alternatives.length} maxLive=${max} finalLive=${current.alternatives.length} finalized=${finalized.length}`); });
console.log(`allocation finalization: ${passed}/10 PASS`);





