import assert from "node:assert/strict";
import type { AllocationBranch, CompensationEvaluationContext, RestBoundary, RestInterval, WeeklyRestComponent } from "../src/rest-engine/types.ts";
import { evaluateCompensation } from "../src/rest-engine/compensation.ts";
import { allocationFrontierAlternative } from "../src/rest-engine/allocation-frontier.ts";
import { transitionCompensationFrontier } from "../src/rest-engine/compensation-frontier.ts";
import { compensationDeadlineForWeek, fixedLegalWeekForInstant, formatLondonInstant, resolveLondonWallTime } from "../src/rest-engine/time.ts";
const H=60*60*1000; let passed=0; function test(id:string,n:string,b:()=>void){b();passed++;console.log(`PASS ${id} — ${n}`)}
function instant(d:string,t="00:00:00"){const v=resolveLondonWallTime(d,t);assert.equal(v.resolution,"VALID");return v.epochMilliseconds as number}
function boundary(e:number,role:RestBoundary["role"]):RestBoundary{const c=formatLondonInstant(e);return{sourceFactIds:["c"],role,time:resolveLondonWallTime(c.wallDate,c.wallTime),epochMilliseconds:e}}
function rest(id:string,start:number,h:number):RestInterval{return{restIntervalId:id,startBoundary:boundary(start,"WORK_END"),endBoundary:boundary(start+h*H,"WORK_START"),startEpochMilliseconds:start,endEpochMilliseconds:start+h*H,observedThroughEpochMilliseconds:start+h*H,elapsedMilliseconds:h*H,elapsedRangeMilliseconds:null,supportingFactIds:[id],state:"CLOSED",provenance:"EXPLICIT",reviewStatus:"CLEAR",reviewReasons:[]}}
function component(id:string, interval:RestInterval,h:number,role:WeeklyRestComponent["role"]="COUNTED"):WeeklyRestComponent{return{componentId:id,restIntervalId:interval.restIntervalId,sourceOptionId:`option:${id}`,componentIndex:0,startEpochMilliseconds:interval.startEpochMilliseconds as number,endEpochMilliseconds:(interval.startEpochMilliseconds as number)+h*H,startOffsetMilliseconds:0,endOffsetMilliseconds:h*H,durationMilliseconds:h*H,classification:h>=45?"REGULAR":"REDUCED",role,provenance:"EXPLICIT",reviewStatus:"CLEAR",reviewReasons:[]}}
function branch(id:string, source:WeeklyRestComponent, week="2026-02-02", extras:WeeklyRestComponent[]=[]):AllocationBranch{const w=fixedLegalWeekForInstant(instant(week));return{branchId:id,branchFingerprint:id,components:[source,...extras],fixedWeekAssignments:source.role==="COUNTED"?[{assignmentId:`a:${id}`,fixedWeekId:week,componentId:source.componentId,assignmentRole:"COUNTED_FOR_FIXED_WEEK",weekStartEpochMilliseconds:w.startEpochMilliseconds,weekEndEpochMilliseconds:w.endEpochMilliseconds}]:[],additionalComponents:[source,...extras].filter((x)=>x.role==="ADDITIONAL"),rollingQualifyingRests:[],rollingCycleResets:[],twoWeekEvaluations:[],reviewStatus:"CLEAR",reviewReasons:[],legalState:"COMPLIANT",invalidReasons:[],sourceOptionIds:[source,...extras].map(x=>x.sourceOptionId)}}
const ctx=(asOf:number):CompensationEvaluationContext=>({asOfEpochMilliseconds:asOf,factualCoverageCompleteThroughAsOf:true});
function both(sourceHours=36.5, repaymentHours=17.5){const sourceRest=rest("source",instant("2026-02-03"),sourceHours);const repayment=rest("repay",instant("2026-02-10"),repaymentHours);const b=branch("source-branch",component("source-component",sourceRest,sourceHours));const old=evaluateCompensation([sourceRest,repayment],[b],ctx(instant("2026-03-01"))).branchEvaluations[0];const alt=allocationFrontierAlternative(b);const next=transitionCompensationFrontier({alternatives:[]},{alternatives:[alt]},[sourceRest,repayment],ctx(instant("2026-03-01")));return{sourceRest,repayment,b,old,next,alt}}
function statuses(e:{obligationResults:{status:string}[]}){return e.obligationResults.map(x=>x.status).sort()}
test("C01","one reduced/simple repayment matches old evaluator",()=>{const x=both();assert.deepEqual(statuses(x.next.nextCompensationFrontier.alternatives[0].evaluation),statuses(x.old));assert.equal(x.old.obligations[0].requiredCompensationMilliseconds,8.5*H)});
test("C02","partial fragments do not become paid",()=>{const x=both(36.5,13);const second=rest("second",instant("2026-02-12"),13);const v=transitionCompensationFrontier({alternatives:[]},{alternatives:[x.alt]},[x.sourceRest,x.repayment,second],ctx(instant("2026-03-01")));assert.notEqual(v.nextCompensationFrontier.alternatives[0].evaluation.obligationResults[0].status,"COMPLETED_ON_TIME")});
test("C03","17h30 plus 8h30 pays separately without source reclassification",()=>{const x=both();assert.equal(x.old.obligations[0].sourceReducedDurationMilliseconds,36.5*H);assert.equal(x.old.obligationResults[0].status,"COMPLETED_ON_TIME")});
test("C04","later rest does not erase overdue finalization",()=>{const x=both(24,30);const late=rest("late",instant("2026-03-10"),30);const v=transitionCompensationFrontier({alternatives:[]},{alternatives:[x.alt]},[x.sourceRest,late],ctx(instant("2026-04-01")));assert.ok(v.newlyFinalizedCompensationResults.some(r=>r.status==="OVERDUE"))});
test("C05","repayment keeps source reduced",()=>assert.equal(both().next.nextCompensationFrontier.alternatives[0].evaluation.obligations[0].sourceReducedDurationMilliseconds,36.5*H));
test("C06","separate obligations retain deterministic ordering",()=>{const x=both();assert.equal(x.next.nextCompensationFrontier.alternatives[0].evaluation.obligations.length,1)});
test("C07","unfit earlier debt does not produce partial credit",()=>{const x=both(24,15);assert.notEqual(x.next.nextCompensationFrontier.alternatives[0].evaluation.obligationResults[0].status,"COMPLETED_ON_TIME")});
test("C08","deadline semantics remain evaluator-owned",()=>{const x=both();assert.ok(x.next.nextCompensationFrontier.alternatives[0].evaluation.obligationResults[0])});
test("C09","allocation alternatives remain branch-correlated",()=>{const x=both();const b2=branch("second",component("second-component",x.sourceRest,24));const v=transitionCompensationFrontier({alternatives:[]},{alternatives:[x.alt,allocationFrontierAlternative(b2)]},[x.sourceRest,x.repayment],ctx(instant("2026-03-01")));assert.ok(v.nextCompensationFrontier.alternatives.length>=2)});
test("C10","additional reduced has no debt",()=>{const r=rest("additional",instant("2026-02-03"),24);const b=branch("additional",component("add",r,24,"ADDITIONAL"));const v=transitionCompensationFrontier({alternatives:[]},{alternatives:[allocationFrontierAlternative(b)]},[r],ctx(instant("2026-03-01")));assert.equal(v.nextCompensationFrontier.alternatives[0].evaluation.obligations.length,0)});
test("C11","paid obligation emits finalized result",()=>assert.ok(both().next.newlyFinalizedCompensationResults.some(r=>r.status==="COMPLETED_ON_TIME")));
test("C12","overdue obligation emits finalized result",()=>{const x=both(24,9);const v=transitionCompensationFrontier({alternatives:[]},{alternatives:[x.alt]},[x.sourceRest],ctx(instant("2026-04-01")));assert.ok(v.newlyFinalizedCompensationResults.some(r=>r.status==="OVERDUE"))});
test("C13","seed reconstructs debt after allocation component finalization",()=>{const x=both();const stripped={...x.alt,countedComponents:[],assignments:[]};const v=transitionCompensationFrontier({alternatives:[]},{alternatives:[stripped]},[x.sourceRest,x.repayment],ctx(instant("2026-03-01")));assert.equal(v.nextCompensationFrontier.alternatives[0].evaluation.obligations.length,1)});
test("C14","future identity includes allocation correlation",()=>{const x=both();const v=transitionCompensationFrontier({alternatives:[]},{alternatives:[x.alt,{...x.alt,alternativeId:"other"}]},[x.sourceRest,x.repayment],ctx(instant("2026-03-01")));assert.ok(v.nextCompensationFrontier.alternatives.length>=2)});
test("C15","manageable multi-week transition remains deterministic",()=>{const a=both();const first=transitionCompensationFrontier({alternatives:[]},{alternatives:[a.alt]},[a.sourceRest,a.repayment],ctx(instant("2026-03-01")));const second=transitionCompensationFrontier(first.nextCompensationFrontier,{alternatives:[a.alt]},[a.sourceRest,a.repayment],ctx(instant("2026-03-01")));assert.deepEqual(statuses(first.nextCompensationFrontier.alternatives[0].evaluation),statuses(second.nextCompensationFrontier.alternatives[0].evaluation));console.log(`C15 metrics: intervals=2 oldBranches=1 maxCompensationFrontier=${first.nextCompensationFrontier.alternatives.length} finalCompensationFrontier=${second.nextCompensationFrontier.alternatives.length}`)});
console.log(`compensation frontier: ${passed}/15 PASS`);


function semantic(e:any){return {obligations:e.obligations.map((o:any)=>[o.sourceComponentId,o.sourceRestIntervalId,o.sourceFixedWeekId,o.requiredCompensationMilliseconds,o.deadlineEpochMilliseconds]).sort(),results:e.obligationResults.map((r:any)=>{const o=e.obligations.find((x:any)=>x.obligationId===r.obligationId);return[o.sourceComponentId,r.status,r.remainingCompensationMilliseconds,r.reviewReasons] }).sort(),blocks:e.blocks.map((b:any)=>[e.obligations.find((o:any)=>o.obligationId===b.obligationId)?.sourceComponentId,b.restIntervalId,b.startEpochMilliseconds,b.endEpochMilliseconds,b.durationMilliseconds,b.reviewStatus]).sort(),attachments:e.attachments.map((a:any)=>[e.obligations.find((o:any)=>o.obligationId===a.obligationId)?.sourceComponentId,a.restIntervalId,a.baseId,a.deadlineCase,a.status,a.packageCompletionEpochMilliseconds]).sort()}}
function direct(branches:AllocationBranch[],intervals:RestInterval[],asOf:number){const old=evaluateCompensation(intervals,branches,ctx(asOf)).branchEvaluations.map(semantic).sort((a,b)=>JSON.stringify(a).localeCompare(JSON.stringify(b)));const alts=branches.map(allocationFrontierAlternative);const next=transitionCompensationFrontier({alternatives:[]},{alternatives:alts},intervals,ctx(asOf));const modern=next.nextCompensationFrontier.alternatives.map(x=>semantic(x.evaluation)).sort((a,b)=>JSON.stringify(a).localeCompare(JSON.stringify(b)));assert.deepEqual(modern,old);return {old,next}}
function reducedSource(id:string,week:string,h:number){const r=rest(`source:${id}`,instant(week,"12:00:00"),h);return{r,c:component(`component:${id}`,r,h),week}}
test("A2D-01","two separate debts preserve source/deadline/order directly",()=>{const a=reducedSource("a","2026-02-02",36),b=reducedSource("b","2026-02-09",40);const payA=rest("payA",instant("2026-02-16"),18),payB=rest("payB",instant("2026-02-23"),16);const br=branch("two",a.c,a.week,[b.c]);br.fixedWeekAssignments.push({...br.fixedWeekAssignments[0],assignmentId:"b",componentId:b.c.componentId,fixedWeekId:b.week,weekStartEpochMilliseconds:fixedLegalWeekForInstant(instant(b.week)).startEpochMilliseconds,weekEndEpochMilliseconds:fixedLegalWeekForInstant(instant(b.week)).endEpochMilliseconds} as any);const d=direct([br],[a.r,b.r,payA,payB],instant("2026-04-01"));assert.equal(d.old[0].obligations.length,2)});
test("A2D-02","earlier large debt unfit/later smaller debt fit directly",()=>{const a=reducedSource("large","2026-02-02",24),b=reducedSource("small","2026-02-09",40);const pay=rest("one-small-capacity",instant("2026-02-16"),14);const br=branch("sizes",a.c,a.week,[b.c]);br.fixedWeekAssignments.push({...br.fixedWeekAssignments[0],assignmentId:"small",componentId:b.c.componentId,fixedWeekId:b.week,weekStartEpochMilliseconds:fixedLegalWeekForInstant(instant(b.week)).startEpochMilliseconds,weekEndEpochMilliseconds:fixedLegalWeekForInstant(instant(b.week)).endEpochMilliseconds});const d=direct([br],[a.r,b.r,pay],instant("2026-04-01"));assert.ok(d.old.length>0)});
test("A2D-03","Case B deadline uncertainty directly matches",()=>{const a=reducedSource("caseb","2026-02-02",36.5);const deadline=compensationDeadlineForWeek(fixedLegalWeekForInstant(instant(a.week)));const pay=rest("caseb-pay",deadline.epochMilliseconds-8.5*H,17.5);const d=direct([branch("caseb",a.c,a.week)],[a.r,pay],deadline.epochMilliseconds+H);assert.ok(d.old.length>0)});
test("A2D-04","branch-heavy multi-week reachable meanings directly match",()=>{const a=reducedSource("ba","2026-02-02",36.5),b=reducedSource("bb","2026-02-09",40);const p=rest("branch-pay",instant("2026-02-16"),18);const one=branch("branch-a",a.c,a.week), two=branch("branch-b",b.c,b.week);const d=direct([one,two],[a.r,b.r,p],instant("2026-04-01"));assert.ok(d.next.nextCompensationFrontier.alternatives.length>=2)});
test("A2D-05","no synthetic cross-branch source combinations",()=>{const a=reducedSource("ca","2026-02-02",36),b=reducedSource("cb","2026-02-09",40);const d=direct([branch("ca",a.c,a.week),branch("cb",b.c,b.week)],[a.r,b.r],instant("2026-04-01"));assert.ok(d.next.nextCompensationFrontier.alternatives.length>=2)});
test("A2D-06","paid finalization equals old paid meaning",()=>{const x=both();const d=direct([x.b],[x.sourceRest,x.repayment],instant("2026-03-01"));assert.ok(d.next.newlyFinalizedCompensationResults.some(x=>x.status==="COMPLETED_ON_TIME"))});
test("A2D-07","overdue finalization equals old overdue meaning",()=>{const x=both(24,9);const d=direct([x.b],[x.sourceRest],instant("2026-04-01"));assert.ok(d.next.newlyFinalizedCompensationResults.some(x=>x.status==="OVERDUE"))});





