import fs from 'node:fs';
import path from 'node:path';

const root = process.cwd();
const pkgPath = path.join(root, 'package.json');
const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
const rawVersion = pkg.version;
if (!/^\d+\.\d+\.\d+/.test(rawVersion)) {
  throw new Error(`Invalid package.json version: ${rawVersion}`);
}
const version = `v${rawVersion}`;
const displayVersion = `V${rawVersion}`;
const cacheVersion = rawVersion.replace(/\./g, '-');

function writeIfChanged(filePath, content) {
  const current = fs.existsSync(filePath) ? fs.readFileSync(filePath, 'utf8') : null;
  if (current !== content) fs.writeFileSync(filePath, content);
}

writeIfChanged(path.join(root, 'src/version.ts'), `// Auto-generated by scripts/sync-version.mjs from package.json.\nexport const APP_VERSION = "${version}";\nexport const APP_VERSION_NUMBER = "${rawVersion}";\nexport const APP_DISPLAY_VERSION = "${displayVersion}";\nexport const APP_TITLE = ` + '`' + `Driver Pay App ${displayVersion}` + '`' + `;\n`);

const indexPath = path.join(root, 'index.html');
let indexHtml = fs.readFileSync(indexPath, 'utf8');
indexHtml = indexHtml.replace(/<title>Driver Pay App v?[0-9]+\.[0-9]+\.[0-9]+<\/title>/i, `<title>Driver Pay App ${version}</title>`);
writeIfChanged(indexPath, indexHtml);

const manifestPath = path.join(root, 'public/manifest.webmanifest');
if (fs.existsSync(manifestPath)) {
  const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
  manifest.name = `Driver Pay App ${version}`;
  manifest.short_name = `Driver Pay ${rawVersion}`;
  manifest.description = `Driver Pay App ${version}`;
  writeIfChanged(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`);
}

const swPath = path.join(root, 'public/sw.js');
if (fs.existsSync(swPath)) {
  let sw = fs.readFileSync(swPath, 'utf8');
  sw = sw.replace(/const CACHE_NAME = "[^"]+";/, `const CACHE_NAME = "driver-pay-v${cacheVersion}";`);
  writeIfChanged(swPath, sw);
}
