// Auto-generated by scripts/sync-version.mjs from package.json.
export const APP_VERSION = "v5.2.5";
export const APP_VERSION_NUMBER = "5.2.5";
export const APP_DISPLAY_VERSION = "V5.2.5";
export const APP_TITLE = `Driver Pay App V5.2.5`;
